name: NeteaseCloud

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Install requests #安装requests
      run: |
        pip install requests
        
    - name: Run main.py #运行main.py
      env:
        ACCOUNT: ${{ secrets.ACCOUNT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API: ${{ secrets.API }}
        KEY: ${{ secrets.KEY }}
      run: |
        python main.py
